import sys
import os
import json
import random
import string
import asyncio
from datetime import datetime
import paramiko

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding='utf-8')
        sys.stderr.reconfigure(encoding='utf-8')
    except Exception:
        pass

import discord
from discord.ext import commands
import config
from trade_watcher import fulfill_order

# ==============================================================================
# 💾 DATABASE HELPERS
# ==============================================================================
def load_data():
    if os.path.exists(config.DATA_FILE):
        with open(config.DATA_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    return {}

def save_data(data):
    with open(config.DATA_FILE, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

def load_orders():
    if os.path.exists(config.ORDERS_FILE):
        with open(config.ORDERS_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    return {}

def save_orders(orders):
    with open(config.ORDERS_FILE, "w", encoding="utf-8") as f:
        json.dump(orders, f, indent=2, ensure_ascii=False)

# ==============================================================================
# 🎮 IN-GAME STEAM LINK VERIFICATION (VIA SFTP TO RUST SERVER)
# ==============================================================================
def verify_ingame_code(code_to_check):
    """
    Connects to Rust server via SFTP and verifies the 6-digit code generated by /link in-game.
    Returns (success, steam_id, player_name, error_msg)
    """
    try:
        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh.connect(config.SFTP_HOST, port=config.SFTP_PORT, username=config.SFTP_USER, password=config.SFTP_PASS, timeout=12)
        sftp = ssh.open_sftp()

        remote_data_file = f"{config.SFTP_BASE_DIR}/oxide/data/SteamLink_Data.json"
        
        try:
            with sftp.open(remote_data_file, "r") as f:
                link_data = json.loads(f.read().decode("utf-8"))
        except Exception:
            link_data = {"PendingCodes": {}, "LinkedSteamIDs": []}

        pending = link_data.get("PendingCodes", {})
        code_str = str(code_to_check).strip()

        if code_str not in pending:
            sftp.close()
            ssh.close()
            return False, None, None, "Code not found or expired. Type `/link` in-game to generate a new one."

        code_info = pending[code_str]
        steam_id = str(code_info.get("SteamID"))
        player_name = code_info.get("PlayerName", "Survivor")

        # Mark as linked on the server
        del pending[code_str]
        linked_list = link_data.get("LinkedSteamIDs", [])
        if int(steam_id) not in linked_list:
            linked_list.append(int(steam_id))
        link_data["LinkedSteamIDs"] = linked_list

        with sftp.open(remote_data_file, "w") as f:
            f.write(json.dumps(link_data, indent=2))

        sftp.close()
        ssh.close()
        return True, steam_id, player_name, None

    except Exception as e:
        print(f"[-] SFTP Link Verification Error: {e}")
        return False, None, None, f"Connection to game server failed: {e}"

# ==============================================================================
# 🤖 ENGLISH AI STORE & COMMUNITY ASSISTANT
# ==============================================================================
def ai_store_manager_response(user_message, user_name, is_steam_linked=False, steam_id=None):
    msg = user_message.lower()

    if any(k in msg for k in ["buy", "vip", "donate", "skin", "skins", "trade", "store", "price", "kit", "elite"]):
        if not is_steam_linked:
            return (
                f"Hello, {user_name}! 👋\n\n"
                f"⚠️ **To purchase VIP with Steam skins, please link your Steam account first!**\n\n"
                f"**How to link:**\n"
                f"1. Connect to our server: `client.connect 157.85.95.101:29416`\n"
                f"2. Type **`/link`** in the in-game chat to get your 6-digit code.\n"
                f"3. Return here and type: **`/link <code>`** (e.g. `/link 482910`)\n\n"
                f"Once linked, you can type **`/buy vip`** to receive a direct trade link!"
            )
        else:
            return (
                f"Hello, {user_name}! Your Steam account (`{steam_id}`) is verified. ✅\n\n"
                f"💎 **Available VIP Tiers on World Project [EU] 2x Trio:**\n"
                f"• **VIP (€5.00 / skins):** Queue Skip, `/kit vip`, `/skinbox`, 2x furnace smelt bonus.\n"
                f"• **VIP+ (€10.00 / skins):** All VIP perks, `/kit vip+`, `/sil` (sign painter), `/boxsort`.\n"
                f"• **ELITE (€15.00 / skins):** Top priority queue, `/kit elite` (AK/Full Metal), Discord Nitro role.\n\n"
                f"👉 Type **`/buy vip`**, **`/buy vipplus`**, or **`/buy elite`** to generate your unique trade link!"
            )

    if any(k in msg for k in ["wipe", "rate", "rates", "ip", "connect", "status", "server"]):
        return (
            f"🎮 **World Project [EU] 2x Trio Specifications:**\n\n"
            f"• **Direct Connect:** Press `F1` in Rust and paste:\n"
            f"```bash\nclient.connect 157.85.95.101:29416\n```\n"
            f"• **Rates:** 2x Resources (Wood, Stone, Metal, Sulfur, Scrap) | 2x Smelting | 2x Stacks\n"
            f"• **Group Limit:** Trio (Strict Maximum 3 Players per base/roam)\n"
            f"• **Wipe Schedule:** Every Thursday @ 14:00 CEST (BP Kept). Monthly Force Wipe."
        )

    return (
        f"Hello, {user_name}! I am the official AI Assistant for **World Project [EU]** 🤖.\n\n"
        f"I can help you with:\n"
        f"• Linking your Steam account (`/link <code>`)\n"
        f"• Buying VIP packages using Steam skins (`/buy <tier>`)\n"
        f"• Server information, wipe schedules, and rules\n\n"
        f"Feel free to ask any question or check <#1544384719230345306>!"
    )

# ==============================================================================
# 🎫 INTERACTIVE TICKET SYSTEM
# ==============================================================================
class TicketCloseView(discord.ui.View):
    def __init__(self):
        super().__init__(timeout=None)

    @discord.ui.button(label="Close Ticket", style=discord.ButtonStyle.danger, emoji="🔒", custom_id="close_ticket_btn")
    async def close_ticket(self, interaction: discord.Interaction, button: discord.ui.Button):
        await interaction.response.send_message("🔒 Closing this ticket in 5 seconds...", ephemeral=False)
        await asyncio.sleep(5)
        try:
            await interaction.channel.delete()
        except Exception as e:
            print(f"Error deleting ticket channel: {e}")

class TicketLauncherView(discord.ui.View):
    def __init__(self):
        super().__init__(timeout=None)

    async def create_ticket(self, interaction: discord.Interaction, ticket_category_name: str, emoji_symbol: str):
        guild = interaction.guild
        user = interaction.user

        # Проверяем существующий тикет
        existing_ch = discord.utils.get(guild.text_channels, name=f"ticket-{user.name.lower()}")
        if existing_ch:
            await interaction.response.send_message(f"⚠️ You already have an open ticket: {existing_ch.mention}", ephemeral=True)
            return

        # Находим категорию поддержки
        category = discord.utils.get(guild.categories, name="🎫 04. SUPPORT & REPORTS")
        if not category:
            category = interaction.channel.category

        # Права доступа
        mod_role = discord.utils.get(guild.roles, name="🔨 | Moderator")
        head_mod = discord.utils.get(guild.roles, name="🛡️ | Head Moderator")
        owner_role = discord.utils.get(guild.roles, name="👑 | Owner")

        overwrites = {
            guild.default_role: discord.PermissionOverwrite(read_messages=False),
            user: discord.PermissionOverwrite(read_messages=True, send_messages=True, embed_links=True, attach_files=True),
            guild.me: discord.PermissionOverwrite(read_messages=True, send_messages=True, manage_channels=True)
        }
        for r in [mod_role, head_mod, owner_role]:
            if r:
                overwrites[r] = discord.PermissionOverwrite(read_messages=True, send_messages=True, embed_links=True)

        ticket_ch = await guild.create_text_channel(
            name=f"ticket-{user.name.lower()}",
            category=category,
            overwrites=overwrites,
            topic=f"Support Ticket for {user} ({user.id}) | Category: {ticket_category_name}"
        )

        embed = discord.Embed(
            title=f"{emoji_symbol} Support Ticket — {ticket_category_name}",
            description=(
                f"Welcome, {user.mention}!\n\n"
                f"Our staff has been notified and will assist you shortly.\n"
                f"Please provide all relevant details below (SteamID, Screenshots, Clips, Order IDs).\n"
                f"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            ),
            color=0x3498DB
        )
        embed.add_field(name="Category", value=f"`{ticket_category_name}`", inline=True)
        embed.add_field(name="Account", value=f"`{user}`", inline=True)
        embed.set_footer(text="Press the button below when your issue is resolved.")

        await ticket_ch.send(content=f"{user.mention}", embed=embed, view=TicketCloseView())
        await interaction.response.send_message(f"✅ Your ticket has been created: {ticket_ch.mention}", ephemeral=True)

    @discord.ui.button(label="Store & VIP Support", style=discord.ButtonStyle.success, emoji="💳", custom_id="tkt_store")
    async def btn_store(self, interaction: discord.Interaction, button: discord.ui.Button):
        await self.create_ticket(interaction, "Store & VIP Support", "💳")

    @discord.ui.button(label="Bug & Technical", style=discord.ButtonStyle.primary, emoji="🐛", custom_id="tkt_tech")
    async def btn_tech(self, interaction: discord.Interaction, button: discord.ui.Button):
        await self.create_ticket(interaction, "Technical & Bug Report", "🐛")

    @discord.ui.button(label="Ban Appeal", style=discord.ButtonStyle.secondary, emoji="⚖️", custom_id="tkt_ban")
    async def btn_ban(self, interaction: discord.Interaction, button: discord.ui.Button):
        await self.create_ticket(interaction, "Ban Appeal", "⚖️")

    @discord.ui.button(label="Report Player / Cheat", style=discord.ButtonStyle.danger, emoji="🚨", custom_id="tkt_report")
    async def btn_report(self, interaction: discord.Interaction, button: discord.ui.Button):
        await self.create_ticket(interaction, "Player & Cheat Report", "🚨")

# ==============================================================================
# 🎮 DISCORD BOT INITIALIZATION
# ==============================================================================
intents = discord.Intents.default()
intents.guilds = True
intents.message_content = True
intents.members = True

bot = commands.Bot(command_prefix="/", intents=intents)

@bot.event
async def on_ready():
    bot.add_view(TicketLauncherView())
    bot.add_view(TicketCloseView())
    print("=" * 60)
    print(f"🤖 World Project AI Bot Online: {bot.user.name} ({bot.user.id})")
    print(f"🌐 Server ID: {config.GUILD_ID}")
    print("=" * 60)

# ==============================================================================
# 🔗 /link <CODE> — IN-GAME VERIFICATION
# ==============================================================================
@bot.command(name="link")
async def cmd_link(ctx, code: str = None):
    """Link your Steam account to Discord using in-game /link code"""
    if not code:
        embed = discord.Embed(
            title="🔗 LINK STEAM ACCOUNT TO DISCORD",
            description=(
                "To link your Steam account, follow these **3 simple steps**:\n\n"
                "1. Connect to our Rust server:\n"
                "```bash\nclient.connect 157.85.95.101:29416\n```\n"
                "2. Type **`/link`** in the in-game chat to get your 6-digit code.\n"
                "3. Return here and type: **`/link <code>`**\n"
                "👉 *Example:* `/link 849201`\n"
                "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            ),
            color=0xF1C40F
        )
        embed.set_footer(text="Verification grants access to the Verified Survivor role and skin trade donations.")
        await ctx.send(embed=embed)
        return

    code_clean = code.strip()
    msg = await ctx.send("⏳ Verifying your code with the Rust server...")

    loop = asyncio.get_running_loop()
    success, steam_id, player_name, err = await loop.run_in_executor(None, verify_ingame_code, code_clean)

    if not success:
        embed_err = discord.Embed(
            title="❌ Verification Failed",
            description=(
                f"**Error:** {err}\n\n"
                "Please make sure you are currently on the server, type **`/link`** in game chat, and copy the 6-digit code."
            ),
            color=0xE74C3C
        )
        await msg.edit(content=None, embed=embed_err)
        return

    # Сохраняем в локальную базу данных
    data = load_data()
    user_id_str = str(ctx.author.id)
    data[user_id_str] = {
        "steam_id": steam_id,
        "player_name": player_name,
        "discord_tag": str(ctx.author),
        "linked_at": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
    }
    save_data(data)

    # Выдаем роль "⚔️ | Verified Survivor"
    role = discord.utils.get(ctx.guild.roles, name="⚔️ | Verified Survivor")
    if role:
        try:
            await ctx.author.add_roles(role)
        except Exception as e:
            print(f"[-] Could not grant role: {e}")

    embed_success = discord.Embed(
        title="🎉 STEAM ACCOUNT SUCCESSFULLY VERIFIED!",
        description=(
            f"Welcome to the community, {ctx.author.mention}!\n\n"
            f"👤 **Player Name:** `{player_name}`\n"
            f"🆔 **SteamID64:** `{steam_id}`\n"
            f"🎖️ **Role Granted:** `⚔️ | Verified Survivor`\n\n"
            f"You can now purchase VIP packages via Steam skins using **`/buy`**!"
        ),
        color=0x2ECC71
    )
    embed_success.set_thumbnail(url=ctx.author.display_avatar.url)
    await msg.edit(content=None, embed=embed_success)

# ==============================================================================
# 🛒 /buy <TIER> — TRADE ORDER CREATION (ENGLISH)
# ==============================================================================
@bot.command(name="buy")
async def cmd_buy(ctx, tier: str = None):
    """Create a personalized Steam Skin trade order for VIP perks"""
    data = load_data()
    user_id_str = str(ctx.author.id)

    if user_id_str not in data:
        embed_unlinked = discord.Embed(
            title="⚠️ Steam Verification Required",
            description=(
                "You cannot purchase donations without a linked Steam account.\n\n"
                "**How to link your Steam account:**\n"
                "1. Connect in-game: `client.connect 157.85.95.101:29416`\n"
                "2. Type **`/link`** in Rust chat to get your 6-digit code.\n"
                "3. Type **`/link <code>`** here in Discord.\n"
                "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            ),
            color=0xE74C3C
        )
        await ctx.send(embed=embed_unlinked)
        return

    steam_id = data[user_id_str]["steam_id"]

    valid_tiers = {
        "vip": ("VIP", "€5.00 / 30 Days", "Queue Skip, /kit vip (SAR, Hazmat, Meds), /skinbox access, 2x Furnace Speed"),
        "vipplus": ("VIP+", "€10.00 / 30 Days", "All VIP perks, /kit vip+ (SMG, Roadsign), /sil sign artist, /boxsort"),
        "vip+": ("VIP+", "€10.00 / 30 Days", "All VIP perks, /kit vip+ (SMG, Roadsign), /sil sign artist, /boxsort"),
        "elite": ("ELITE", "€15.00 / 30 Days", "Highest Queue Priority, /kit elite (AK/Full Metal), Discord Nitro Role")
    }

    if not tier or tier.lower() not in valid_tiers:
        embed_menu = discord.Embed(
            title="🛒 CHOOSE YOUR VIP MEMBERSHIP TIER",
            description=(
                "Please specify which tier you would like to purchase:\n\n"
                "• **`/buy vip`** — VIP Tier *(€5.00 in skins)*\n"
                "• **`/buy vipplus`** — VIP+ Tier *(€10.00 in skins)*\n"
                "• **`/buy elite`** — ELITE Tier *(€15.00 in skins)*\n\n"
                "🌐 *Or visit our webstore directly:* [worldproject.tebex.io](https://worldproject.tebex.io)"
            ),
            color=0xF1C40F
        )
        await ctx.send(embed=embed_menu)
        return

    tier_clean = "vipplus" if tier.lower() in ["vipplus", "vip+"] else tier.lower()
    title_name, price_str, perks_summary = valid_tiers[tier_clean]

    order_id = "WP-" + "".join(random.choices(string.ascii_uppercase + string.digits, k=6))
    security_token = "".join(random.choices(string.digits, k=4))

    orders = load_orders()
    orders[order_id] = {
        "discord_id": user_id_str,
        "steam_id": steam_id,
        "tier": tier_clean,
        "security_token": security_token,
        "created_at": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
        "status": "pending"
    }
    save_orders(orders)

    embed_order = discord.Embed(
        title=f"📦 STEAM TRADE ORDER #{order_id}",
        description=(
            f"👤 **Customer:** {ctx.author.mention}\n"
            f"🆔 **Verified SteamID:** `{steam_id}`\n"
            f"💎 **Selected Tier:** `{title_name}` ({price_str})\n\n"
            f"### 📋 Skin Payment Instructions:\n"
            f"1. Click the **[Trade URL]({config.BOT_STEAM_TRADE_URL})** link below.\n"
            f"2. Select Rust or CS2 skins from your inventory equal to **{price_str}**.\n"
            f"3. ⚠️ **CRITICAL: You MUST include your Order ID in the trade offer message:**\n"
            f"```text\n{order_id}\n```\n"
            f"4. Send the trade. Once accepted, your VIP activates in-game **instantly**!\n\n"
            f"👉 **[CLICK HERE TO SEND STEAM TRADE OFFER]({config.BOT_STEAM_TRADE_URL})**"
        ),
        color=0x9B59B6
    )
    embed_order.add_field(name="Included Perks", value=perks_summary, inline=False)
    embed_order.set_footer(text=f"Order valid for 60 minutes • Server: World Project [EU] 2x")
    await ctx.send(embed=embed_order)

# ==============================================================================
# 🎟️ /ticketpanel — DEPLOY TICKET EMBED (ADMIN ONLY)
# ==============================================================================
@bot.command(name="ticketpanel")
@commands.has_permissions(administrator=True)
async def cmd_deploy_tickets(ctx):
    embed = discord.Embed(
        title="📩 WORLD PROJECT | SUPPORT TICKETS",
        description=(
            "Need help, have an issue with the store, or want to report a rule breaker?\n\n"
            "Click on the relevant button below to open a private ticket with our staff team:\n\n"
            "💳 **Store & VIP Support** — Payment issues, skin trade confirmation, kit inquiries.\n"
            "🐛 **Bug & Technical** — In-game glitches, connection or server errors.\n"
            "⚖️ **Ban Appeal** — Submit a formal request to appeal an in-game or Discord ban.\n"
            "🚨 **Report Player** — Report hackers, macro abusers, or team limit violations.\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        ),
        color=0x3498DB
    )
    embed.set_footer(text="World Project EU • Tickets are answered 24/7 by our moderation team")
    await ctx.send(embed=embed, view=TicketLauncherView())

# ==============================================================================
# 🤖 AI CHAT LISTENER
# ==============================================================================
@bot.event
async def on_message(message):
    if message.author.bot:
        return

    if bot.user.mentioned_in(message) or message.content.startswith("?"):
        clean_content = message.content.replace(f"<@{bot.user.id}>", "").strip("? ")
        data = load_data()
        user_info = data.get(str(message.author.id))
        is_linked = user_info is not None
        steam_id = user_info["steam_id"] if is_linked else None

        response = ai_store_manager_response(clean_content, message.author.display_name, is_linked, steam_id)
        await message.reply(response)

    await bot.process_commands(message)

if __name__ == "__main__":
    if not config.DISCORD_TOKEN:
        print("[-] Error: DISCORD_TOKEN is missing in config/environment!")
        sys.exit(1)
    bot.run(config.DISCORD_TOKEN)
